export const COMPONENT_IDS = {
  LIST_TIMEOUT_EDIT: 'list-timeout-edit',
  LIST_EVENT_DAY: 'list-event-day',
  ADD_EVENT_DAY: 'add-event-day',
  ADD_PHASE_LANE: 'add-phase-lane',
  CALENDAR_PHASE_ITEM: 'calendar-phase-item',
  NAVBAR_TIMEOUTS: 'navbar-timeouts',
  NAVBAR_LIST_EVENT: 'navbar-list-event',
  NAVBAR_MAIN_CALENDAR: 'navbar-main-calendar',
  NAVBAR_CURRENT_USER: 'navbar-current-user',
  NAVBAR_LANDING_PAGE: 'navbar-landing-page',
  NAVBAR_COLLAPSE: 'navbar-collapse',
  NAVBAR_LOGIN_DROPDOWN: 'navbar-login-dropdown',
  NAVBAR_LOGIN_DROPDOWN_SIGN_IN: 'navbar-login-dropdown-sign-in',
  NAVBAR_LOGIN_DROPDOWN_SIGN_UP: 'navbar-login-dropdown-sign-up',
  NAVBAR_SIGN_OUT: 'navbar-sign-out',
  NAVBAR_CONTACT: 'navbar-contact',
  SIGN_IN_FORM_EMAIL: 'sign-in-form-email',
  SIGN_IN_FORM_PASSWORD: 'sign-in-form-password',
  SIGN_IN_FORM_SUBMIT: 'sign-in-form-submit',
  SIGN_UP_FORM_FIRST_NAME: 'sign-up-form-first-name',
  SIGN_UP_FORM_LAST_NAME: 'sign-up-form-last-name',
  SIGN_UP_FORM_EMAIL: 'sign-up-form-email',
  SIGN_UP_FORM_PASSWORD: 'sign-up-form-password',
  SIGN_UP_FORM_SUBMIT: 'sign-up-form-submit',
  
};
