/** Define ids for each page. */
export const PAGE_IDS = {
  ADD_HOLIDAY: 'add-holiday',
  ADD_EVENT: 'add-event',
  ADD_TIMEOUT: 'add-timeout',
  LIST_EVENTSDAY: 'list-eventsday',
  EDIT_EVENT_DAY: 'edit-event-day',
  LIST_TIMEOUT: 'list-timeout',
  EDIT_TIMEOUT: 'edit-timeout',
  LANDING: 'landing',
  MAIN_CALENDAR: 'main-calendar',
  LIST_STUFF: 'list-stuff',
  LIST_STUFF_ADMIN: 'list-stuff-admin',
  MANAGE_DATABASE: 'manage-database',
  NOT_AUTHORIZED: 'not-authorized',
  NOT_FOUND: 'not-found',
  SIGN_IN: 'sign-in',
  SIGN_OUT: 'sign-out',
  SIGN_UP: 'sign-up',
};
